<div class="divRecipeSummary">
	<div class="divRecipeSumImg">
		<img src='images/test.png' />
	</div>
	<div>
		<div class="divRecipeSumName">
			<a href="recipe.php?id=1">
			Clam Chowder
			</a>
		</div>
		<div class="divRecipeSumDesc">
			A delicious, traditional, cream based chowder, this recipe calls for the standard chowder ingredients: onion, celery, potatoes, diced carrots, clams, and cream. A little red wine vinegar is added before serving for extra flavor.
		</div>
	</div>
</div>