<div id="weekcontainer" class="container">
	<div class="day">
		<div id="weekviewsundaytitle" class="daytitle">
			<span>SUN</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div class="day">
		<div class="daytitle">
			<span>MON</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div class="day">
		<div class="daytitle">
			<span>TUES</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div class="day">
		<div class="daytitle">
			<span>WED</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div class="day">
		<div class="daytitle">
			<span>THUR</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div class="day">
		<div class="daytitle">
			<span>FRI</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
	
	<div id="weekviewsaturday" class="day">
		<div class="daytitle">
			<span>SAT</span>
		</div>
		<div class="daycontent">
			<div class="divmeal">
				<span>lunch</span>
			</div>
			<div class="divmeal">
				<span>dinner</span>
			</div>
		</div>
	</div>
</div>
