<div id="divWeekview">
	<div class="weekviewday well">
		<div class="weekviewdayname">Sunday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Monday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Tuesday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Wednesday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Thursday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Friday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
	<div class="weekviewday well">
		<div class="weekviewdayname">Saturday</div>
		<div class="row well well-sm">breakfast</div>
		<div class="row well well-sm">lunch</div>
		<div class="row well well-sm">dinner</div>
	</div>
</div>